[package]
name = "os-bindings-napi"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["napi9"] }
napi-derive = "2"
audio-capture = { path = "../audio-capture" }
os-integration = { path = "../os-integration" }
tokio = { version = "1", features = ["rt", "sync", "macros"] }

[build-dependencies]
napi-build = "2"
