#!/usr/bin/env python3
"""Generate the three-arm style-spike v4 profiles + corpus.

v4 re-runs v3's card experiment with the confound removed. v3's `card` arm
appended the same prose card used here but was measured against a baseline
whose own system prompt says "preserve ... word choice; do not paraphrase" —
which forbids exactly what the card asks the model to do. v3's FAIL verdict
was withdrawn because it could not distinguish "the card doesn't work" from
"the model obeyed the older, more specific instruction not to touch word
choice". v4 isolates the clause as the single variable:

  baseline  = the shipped prompt, verbatim (same as v2/v3's baseline)
  conflict  = shipped prompt + prose card, UNCHANGED preservation clause —
              this reproduces v3's card arm in-run, as the control
  amended   = shipped prompt with the preservation clause amended to permit
              tone/word-choice adaptation, + the SAME prose card

Reuses `derive-style-spike-v2.py`'s `CARD` prose dict verbatim (imported, not
retyped) — the card must be byte-identical to v3's for the comparison to
mean anything. Drops v2's `CEILING`: v4 has no ceiling arm, `conflict` is the
control.

The amendment is string surgery on the shipped prompt fetched via
`lirevo-eval print-shipped-prompt`, never a transcribed copy: if the shipped
prompt has been reworded since v2/v3, `amend()` asserts loudly instead of
silently producing an `amended` arm identical to `conflict`.

Emits two committed artifacts, read by `lirevo-eval run`:

  crates/lirevo-eval/data/profiles/style-spike-v4.toml
  crates/lirevo-eval/data/corpus/style-spike-v4.jsonl

Each source case is emitted three times — once per arm — keeping `transcript`
and `expected` byte-identical across arms so the only variable is the system
prompt the profile carries. Run from the repo root:

    python3 scripts/derive-style-spike-v4.py
"""

import importlib.util
import json
import pathlib
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SEED = REPO / "crates/lirevo-eval/data/corpus/v1-seed.jsonl"
OUT_PROFILES = REPO / "crates/lirevo-eval/data/profiles/style-spike-v4.toml"
OUT = REPO / "crates/lirevo-eval/data/corpus/style-spike-v4.jsonl"

# `derive-style-spike-v2.py` has a hyphen in its filename, so it cannot be
# reached via a normal `import` statement; load it by explicit file path.
_v2_spec = importlib.util.spec_from_file_location(
    "derive_style_spike_v2", REPO / "scripts" / "derive-style-spike-v2.py"
)
_v2 = importlib.util.module_from_spec(_v2_spec)
_v2_spec.loader.exec_module(_v2)
CARD = _v2.CARD

SOURCE_LANGS = {"it", "en"}
LANGS = ("it", "en")

HEADER = """\
# GENERATED by scripts/derive-style-spike-v4.py — DO NOT HAND-EDIT.
# Three-arm style-card experiment, v4 (Gate 1, re-run with the preservation
# clause amended after v3's FAIL verdict was withdrawn as confounded — see
# scripts/derive-style-spike-v4.py for the full rationale).
#
# baseline        = lirevo_prompts::build_clean_system_prompt(lang), verbatim —
#                    obtained via `lirevo-eval print-shipped-prompt`, never
#                    hand-transcribed. This is what a Lirevo user gets today.
# conflict_casual = baseline + the SAME prose casual card as v2/v3, UNCHANGED
#                    preservation clause — reproduces v3's card arm in-run
# conflict_formal = baseline + the SAME prose formal card as v2/v3, UNCHANGED
#                    preservation clause
# amended_casual   = baseline with the preservation clause amended (string
#                    surgery, see amend() below) + the SAME prose casual card
# amended_formal   = baseline with the preservation clause amended + the SAME
#                    prose formal card
#
# post_assertions are IDENTICAL across all five on purpose: the only variable
# under test is the system prompt. They feed assertions_passed/total, never
# chrf or judge_style, so they cannot affect the verdict — but letting them
# vary would break the control for no benefit.
"""

CLAUSE_OLD = (
    "- preserve the speaker's meaning, intent, tone, and word choice; "
    "do not paraphrase, summarize, add content, or change the substance"
)
CLAUSE_NEW = (
    "- preserve the speaker's meaning, intent, and substance; never summarize, "
    "add content, or change what is being said\n"
    "- adapt tone, register, punctuation, and word choice to the user's "
    "established style described below"
)


def amend(prompt: str) -> str:
    # Fail loudly rather than silently producing an unamended arm: if the
    # shipped prompt is reworded, this experiment must stop, not quietly
    # measure baseline three times.
    assert CLAUSE_OLD in prompt, (
        "the preservation clause was not found in the shipped prompt; "
        "it was reworded — update CLAUSE_OLD and re-check the design"
    )
    return prompt.replace(CLAUSE_OLD, CLAUSE_NEW)


def toml_multiline(s: str) -> str:
    # TOML """...""" tolerates a lone " but not """, and cannot end with ".
    # Assert rather than escape: a silent corruption here would produce a
    # subtly wrong prompt and a meaningless experiment.
    assert '"""' not in s, "prompt contains a TOML multi-line terminator"
    assert not s.endswith('"'), "prompt ends with a quote; TOML would mis-parse"
    return f'"""{s}"""'


def shipped_prompt(lang: str) -> str:
    proc = subprocess.run(
        [
            "cargo",
            "run",
            "-q",
            "-p",
            "lirevo-eval",
            "--",
            "print-shipped-prompt",
            "--language",
            lang,
        ],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        print(
            f"print-shipped-prompt --language {lang} exited {proc.returncode}:\n{proc.stderr}",
            file=sys.stderr,
        )
        raise SystemExit(1)
    if not proc.stdout:
        print(
            f"print-shipped-prompt --language {lang} produced an empty prompt; "
            "refusing to build a meaningless experiment on it",
            file=sys.stderr,
        )
        raise SystemExit(1)
    return proc.stdout


def emit_profiles(baseline: dict) -> str:
    amended = {lang: amend(baseline[lang]) for lang in LANGS}
    arms = {
        "baseline": {lang: baseline[lang] for lang in LANGS},
        "conflict_casual": {
            lang: baseline[lang] + "\n\n" + CARD["casual"][lang] for lang in LANGS
        },
        "conflict_formal": {
            lang: baseline[lang] + "\n\n" + CARD["formal"][lang] for lang in LANGS
        },
        "amended_casual": {
            lang: amended[lang] + "\n\n" + CARD["casual"][lang] for lang in LANGS
        },
        "amended_formal": {
            lang: amended[lang] + "\n\n" + CARD["formal"][lang] for lang in LANGS
        },
    }
    out = [HEADER]
    for name, prompts in arms.items():
        out.append(f"\n[profile.{name}]")
        out.append("post_assertions = [")
        out.append('  { kind = "max_length_chars", value = 4000 },')
        out.append("]")
        out.append(f"\n[profile.{name}.system_prompts]")
        for lang in LANGS:
            out.append(f"{lang} = {toml_multiline(prompts[lang])}")
        out.append("")
    return "\n".join(out) + "\n"


# source profile -> {arm role: profile name in style-spike-v4.toml}
ARMS_BY_SOURCE = {
    "chat_casual": {
        "baseline": "baseline",
        "conflict": "conflict_casual",
        "amended": "amended_casual",
    },
    "mail_formal": {
        "baseline": "baseline",
        "conflict": "conflict_formal",
        "amended": "amended_formal",
    },
}


def main() -> int:
    if not SEED.exists():
        print(f"input not found: {SEED}", file=sys.stderr)
        return 1

    baseline = {lang: shipped_prompt(lang) for lang in LANGS}
    OUT_PROFILES.write_text(emit_profiles(baseline), encoding="utf-8")
    print(f"wrote 5 profiles → {OUT_PROFILES}")

    rows = []
    sources = 0
    for line in SEED.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        case = json.loads(line)
        arms = ARMS_BY_SOURCE.get(case["profile"])
        if arms is None or case["language"] not in SOURCE_LANGS:
            continue
        sources += 1
        for arm, profile in arms.items():
            out = dict(case)
            out["id"] = f"{case['id']}-{arm}"
            out["profile"] = profile
            out["tags"] = sorted(set(case.get("tags", [])) | {"style-spike-v4", f"arm:{arm}"})
            out["notes"] = (
                f"style-spike-v4 arm={arm} (profile {profile}); derived from "
                f"{case['id']} (source profile {case['profile']}). Generated by "
                f"scripts/derive-style-spike-v4.py — do not hand-edit."
            )
            rows.append(out)

    if not rows:
        print("no source cases matched; refusing to write an empty corpus", file=sys.stderr)
        return 1

    OUT.write_text(
        "".join(json.dumps(r, ensure_ascii=False) + "\n" for r in rows),
        encoding="utf-8",
    )
    print(f"wrote {len(rows)} cases ({sources} source cases × 3 arms) → {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
