#!/usr/bin/env python3
"""Generate the three-arm style-spike v2 profiles + corpus.

v2 fixes the two findings from Gate 1 v1:
1. v1's `baseline` was a hand-written profile, never the prompt Lirevo
   actually ships. v2's `baseline` is `lirevo_prompts::build_clean_system_prompt`
   itself, obtained by shelling out to `lirevo-eval print-shipped-prompt` —
   never hand-transcribed — so the eval's baseline cannot silently diverge
   from the shipped prompt again.
2. v1's card was a structured field list, which turned out to be inert. v2's
   card and ceiling are prose, appended after the shipped baseline.

Emits two committed artifacts, read by `lirevo-eval run`:

  crates/lirevo-eval/data/profiles/style-spike-v2.toml
  crates/lirevo-eval/data/corpus/style-spike-v2.jsonl

Each source case is emitted three times — once per arm — keeping `transcript`
and `expected` byte-identical across arms so the only variable is the system
prompt the profile carries. The card and ceiling arms are mapped to the card
matching the source's OWN style: handing a casual card to a formal case would
score a casual output against a formal reference and make a working card look
broken. Run from the repo root:

    python3 scripts/derive-style-spike-v2.py
"""

import json
import pathlib
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SEED = REPO / "crates/lirevo-eval/data/corpus/v1-seed.jsonl"
OUT_PROFILES = REPO / "crates/lirevo-eval/data/profiles/style-spike-v2.toml"
OUT = REPO / "crates/lirevo-eval/data/corpus/style-spike-v2.jsonl"

SOURCE_LANGS = {"it", "en"}
LANGS = ("it", "en")

HEADER = """\
# GENERATED by scripts/derive-style-spike-v2.py — DO NOT HAND-EDIT.
# Three-arm style-card experiment, v2 (Gate 1 of the style-bootstrapping spike,
# re-run after v1 tested the wrong baseline with an inert card format).
#
# baseline       = lirevo_prompts::build_clean_system_prompt(lang), verbatim —
#                   obtained via `lirevo-eval print-shipped-prompt`, never
#                   hand-transcribed. This is what a Lirevo user gets today.
# card_casual    = baseline + a short, distillable prose casual style block
# card_formal    = baseline + a short, distillable prose formal style block
# ceiling_casual = baseline + a rich, hand-tuned prose casual style block
# ceiling_formal = baseline + a rich, hand-tuned prose formal style block
#
# post_assertions are IDENTICAL across all five on purpose: the only variable
# is the system prompt. They feed assertions_passed/total, never chrf or
# judge_style, so they cannot affect the verdict — but letting them vary would
# break the control for no benefit.
"""

# The only prompt text this script owns. `baseline` comes from the shipped
# prompt itself, never from here.
CARD = {  # short, distillable — what a background distiller could realistically emit
    "casual": {
        "it": "Questo utente scrive in modo colloquiale: frasi brevi, minuscole, punteggiatura minima, nessun saluto e nessuna firma.",
        "en": "This user writes casually: short sentences, lowercase, minimal punctuation, no greeting and no sign-off.",
    },
    "formal": {
        "it": "Questo utente scrive in modo formale: email complete con saluto di apertura, forma di cortesia, frasi intere e formula di chiusura.",
        "en": "This user writes formally: complete emails with an opening greeting, polite register, full sentences and a closing sign-off.",
    },
}

CEILING = {  # rich, hand-tuned — the best a human can write
    "casual": {
        "it": "Adatta il testo allo stile abituale dell'utente in questo contesto: un messaggio WhatsApp/Telegram. Tono colloquiale, frasi brevi. Minuscole accettate; punteggiatura essenziale. Mantieni il punto interrogativo se è una domanda. Niente saluti formali, niente firma. Non aggiungere segnaposto come [Nome].",
        "en": "Match the text to this user's established style in this context: a WhatsApp/Telegram message. Casual tone, short sentences. Lowercase is fine; light punctuation. Keep the question mark if it is a question. No formal greetings or sign-offs. Do not add placeholders such as [Name].",
    },
    "formal": {
        "it": "Adatta il testo allo stile abituale dell'utente in questo contesto: un'email formale. Inizia con un'apertura adeguata (Buongiorno, Gentile ...). Usa la forma di cortesia (Lei, La, Le); mai il tu. Chiudi con una formula adeguata (Cordiali saluti, Distinti saluti). Non inventare né lasciare segnaposto come [Nome] o [Il tuo nome]: se non conosci un nome, ometti il campo.",
        "en": "Match the text to this user's established style in this context: a formal email. Start with an appropriate opening (Dear ..., Hello ...). Use a polite, professional register and full sentences. Close with a formal sign-off (Best regards, Kind regards). Do not invent or leave placeholders such as [Name] or [Your name]: if you do not know a name, omit the field.",
    },
}


def toml_multiline(s: str) -> str:
    # TOML """...""" tolerates a lone " but not """, and cannot end with ".
    # Assert rather than escape: a silent corruption here would produce a
    # subtly wrong prompt and a meaningless experiment.
    assert '"""' not in s, "prompt contains a TOML multi-line terminator"
    assert not s.endswith('"'), "prompt ends with a quote; TOML would mis-parse"
    return f'"""{s}"""'


def shipped_prompt(lang: str) -> str:
    proc = subprocess.run(
        [
            "cargo",
            "run",
            "-q",
            "-p",
            "lirevo-eval",
            "--",
            "print-shipped-prompt",
            "--language",
            lang,
        ],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        print(
            f"print-shipped-prompt --language {lang} exited {proc.returncode}:\n{proc.stderr}",
            file=sys.stderr,
        )
        raise SystemExit(1)
    if not proc.stdout:
        print(
            f"print-shipped-prompt --language {lang} produced an empty prompt; "
            "refusing to build a meaningless experiment on it",
            file=sys.stderr,
        )
        raise SystemExit(1)
    return proc.stdout


def emit_profiles(baseline: dict) -> str:
    arms = {
        "baseline": {lang: baseline[lang] for lang in LANGS},
        "card_casual": {
            lang: baseline[lang] + "\n\n" + CARD["casual"][lang] for lang in LANGS
        },
        "card_formal": {
            lang: baseline[lang] + "\n\n" + CARD["formal"][lang] for lang in LANGS
        },
        "ceiling_casual": {
            lang: baseline[lang] + "\n\n" + CEILING["casual"][lang] for lang in LANGS
        },
        "ceiling_formal": {
            lang: baseline[lang] + "\n\n" + CEILING["formal"][lang] for lang in LANGS
        },
    }
    out = [HEADER]
    for name, prompts in arms.items():
        out.append(f"\n[profile.{name}]")
        out.append("post_assertions = [")
        out.append('  { kind = "max_length_chars", value = 4000 },')
        out.append("]")
        out.append(f"\n[profile.{name}.system_prompts]")
        for lang in LANGS:
            out.append(f"{lang} = {toml_multiline(prompts[lang])}")
        out.append("")
    return "\n".join(out) + "\n"


# source profile -> {arm role: profile name in style-spike-v2.toml}
ARMS_BY_SOURCE = {
    "chat_casual": {
        "baseline": "baseline",
        "card": "card_casual",
        "ceiling": "ceiling_casual",
    },
    "mail_formal": {
        "baseline": "baseline",
        "card": "card_formal",
        "ceiling": "ceiling_formal",
    },
}


def main() -> int:
    if not SEED.exists():
        print(f"input not found: {SEED}", file=sys.stderr)
        return 1

    baseline = {lang: shipped_prompt(lang) for lang in LANGS}
    OUT_PROFILES.write_text(emit_profiles(baseline), encoding="utf-8")
    print(f"wrote 5 profiles → {OUT_PROFILES}")

    rows = []
    sources = 0
    for line in SEED.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        case = json.loads(line)
        arms = ARMS_BY_SOURCE.get(case["profile"])
        if arms is None or case["language"] not in SOURCE_LANGS:
            continue
        sources += 1
        for arm, profile in arms.items():
            out = dict(case)
            out["id"] = f"{case['id']}-{arm}"
            out["profile"] = profile
            out["tags"] = sorted(set(case.get("tags", [])) | {"style-spike-v2", f"arm:{arm}"})
            out["notes"] = (
                f"style-spike-v2 arm={arm} (profile {profile}); derived from "
                f"{case['id']} (source profile {case['profile']}). Generated by "
                f"scripts/derive-style-spike-v2.py — do not hand-edit."
            )
            rows.append(out)

    if not rows:
        print("no source cases matched; refusing to write an empty corpus", file=sys.stderr)
        return 1

    OUT.write_text(
        "".join(json.dumps(r, ensure_ascii=False) + "\n" for r in rows),
        encoding="utf-8",
    )
    print(f"wrote {len(rows)} cases ({sources} source cases × 3 arms) → {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
