#!/usr/bin/env python3
"""Generate the three-arm style-spike profiles + corpus.

Emits two committed artifacts, read by `lirevo-eval run`:

  crates/lirevo-eval/data/profiles/style-spike.toml
  crates/lirevo-eval/data/corpus/style-spike.jsonl

Prompts are READ FROM v1.toml, never transcribed here — v1.toml stays the
single source. The generated files are committed so the experiment is
hermetic and past reports stay re-derivable; rerun this script deliberately
after a v1.toml change.

Each source case is emitted three times — once per arm — keeping `transcript`
and `expected` byte-identical across arms so the only variable is the system
prompt the profile carries. The card and ceiling arms are mapped to the card
matching the source's OWN style: handing a casual card to a formal case would
score a casual output against a formal reference and make a working card look
broken. Run from the repo root:

    python3 scripts/derive-style-spike.py
"""

import json
import pathlib
import sys
import tomllib

REPO = pathlib.Path(__file__).resolve().parent.parent
V1 = REPO / "crates/lirevo-eval/data/profiles/v1.toml"
SEED = REPO / "crates/lirevo-eval/data/corpus/v1-seed.jsonl"
OUT_PROFILES = REPO / "crates/lirevo-eval/data/profiles/style-spike.toml"
OUT = REPO / "crates/lirevo-eval/data/corpus/style-spike.jsonl"

SOURCE_LANGS = {"it", "en"}
LANGS = ("it", "en")

HEADER = """\
# GENERATED by scripts/derive-style-spike.py — DO NOT HAND-EDIT.
# Three-arm style-card experiment (Gate 1 of the style-bootstrapping spike).
#
# Prompts are copied from v1.toml at generation time; this file is committed
# so the experiment is hermetic and past reports stay re-derivable. Rerun the
# generator deliberately after a v1.toml change.
#
# baseline       = plain, verbatim (the floor; style-agnostic)
# card_casual    = plain + a structured casual card (the hypothesis)
# card_formal    = plain + a structured formal card (the hypothesis)
# ceiling_casual = chat_casual, verbatim (upper bound)
# ceiling_formal = mail_formal, verbatim (upper bound)
#
# post_assertions are IDENTICAL across all five on purpose: the only variable
# is the system prompt. They feed assertions_passed/total, never chrf or
# judge_style, so they cannot affect the verdict — but letting them vary would
# break the control for no benefit.
"""

# The only prompt text this script owns. Everything else comes from v1.toml.
CARDS = {
    "casual": {
        "it": """Stile abituale dell'utente in questo contesto:
- Tono: colloquiale
- Formalità: 2/5
- Saluto: nessuno
- Firma: nessuna
- Lessico: frasi brevi, minuscole accettate, punteggiatura essenziale, emoji rare
Adatta il testo ripulito a questo stile.""",
        "en": """This user's established style in this context:
- Tone: casual
- Formality: 2/5
- Greeting: none
- Sign-off: none
- Vocabulary: short sentences, lowercase accepted, light punctuation, emoji rare
Match the cleaned text to this style.""",
    },
    "formal": {
        "it": """Stile abituale dell'utente in questo contesto:
- Tono: professionale
- Formalità: 5/5
- Saluto: presente (Buongiorno, Gentile ...)
- Firma: presente (Cordiali saluti)
- Lessico: frasi complete, forma di cortesia (Lei), punteggiatura completa
Adatta il testo ripulito a questo stile.""",
        "en": """This user's established style in this context:
- Tone: professional
- Formality: 5/5
- Greeting: present (Dear ..., Hello ...)
- Sign-off: present (Best regards)
- Vocabulary: full sentences, polite register, complete punctuation
Match the cleaned text to this style.""",
    },
}


def toml_multiline(s: str) -> str:
    # TOML """...""" tolerates a lone " but not """, and cannot end with ".
    # Assert rather than escape: a silent corruption here would produce a
    # subtly wrong prompt and a meaningless experiment.
    assert '"""' not in s, "prompt contains a TOML multi-line terminator"
    assert not s.endswith('"'), "prompt ends with a quote; TOML would mis-parse"
    return f'"""{s}"""'


def emit_profiles(v1: dict) -> str:
    plain = v1["profile"]["plain"]["system_prompts"]
    arms = {
        "baseline": {lang: plain[lang] for lang in LANGS},
        "card_casual": {
            lang: plain[lang] + "\n\n" + CARDS["casual"][lang] for lang in LANGS
        },
        "card_formal": {
            lang: plain[lang] + "\n\n" + CARDS["formal"][lang] for lang in LANGS
        },
        "ceiling_casual": {
            lang: v1["profile"]["chat_casual"]["system_prompts"][lang] for lang in LANGS
        },
        "ceiling_formal": {
            lang: v1["profile"]["mail_formal"]["system_prompts"][lang] for lang in LANGS
        },
    }
    out = [HEADER]
    for name, prompts in arms.items():
        out.append(f"\n[profile.{name}]")
        out.append("post_assertions = [")
        out.append('  { kind = "max_length_chars", value = 4000 },')
        out.append("]")
        out.append(f"\n[profile.{name}.system_prompts]")
        for lang in LANGS:
            out.append(f"{lang} = {toml_multiline(prompts[lang])}")
        out.append("")
    return "\n".join(out) + "\n"


# source profile -> {arm role: profile name in style-spike.toml}
ARMS_BY_SOURCE = {
    "chat_casual": {
        "baseline": "baseline",
        "card": "card_casual",
        "ceiling": "ceiling_casual",
    },
    "mail_formal": {
        "baseline": "baseline",
        "card": "card_formal",
        "ceiling": "ceiling_formal",
    },
}


def main() -> int:
    for p in (SEED, V1):
        if not p.exists():
            print(f"input not found: {p}", file=sys.stderr)
            return 1

    v1 = tomllib.loads(V1.read_text(encoding="utf-8"))
    OUT_PROFILES.write_text(emit_profiles(v1), encoding="utf-8")
    print(f"wrote 5 profiles → {OUT_PROFILES}")

    rows = []
    sources = 0
    for line in SEED.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        case = json.loads(line)
        arms = ARMS_BY_SOURCE.get(case["profile"])
        if arms is None or case["language"] not in SOURCE_LANGS:
            continue
        sources += 1
        for arm, profile in arms.items():
            out = dict(case)
            out["id"] = f"{case['id']}-{arm}"
            out["profile"] = profile
            out["tags"] = sorted(set(case.get("tags", [])) | {"style-spike", f"arm:{arm}"})
            out["notes"] = (
                f"style-spike arm={arm} (profile {profile}); derived from "
                f"{case['id']} (source profile {case['profile']}). Generated by "
                f"scripts/derive-style-spike.py — do not hand-edit."
            )
            rows.append(out)

    if not rows:
        print("no source cases matched; refusing to write an empty corpus", file=sys.stderr)
        return 1

    OUT.write_text(
        "".join(json.dumps(r, ensure_ascii=False) + "\n" for r in rows),
        encoding="utf-8",
    )
    print(f"wrote {len(rows)} cases ({sources} source cases × 3 arms) → {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
