#!/usr/bin/env python3
"""Generate the two-arm style-spike v5 profiles + corpus.

v5 is Gate 1's last question: v1-v4 killed the style *card* (description
appended to the prompt) — a 1B echoes descriptions and obeys imperatives, and
both forms flatline on the casual direction the product actually needs. The
one mechanism left untested is the one already shipped in v0.9: few-shot
raw->final pairs, via `lirevo_prompts::build_clean_system_prompt_with_examples`.
They neither describe nor command — they *show*.

Two arms only (not three, unlike v1-v4):

  baseline = lirevo_prompts::build_clean_system_prompt(lang), verbatim
  fewshot  = lirevo_prompts::build_clean_system_prompt_with_examples(lang, EXAMPLES)

Both are obtained by shelling out to `lirevo-eval print-shipped-prompt`, never
hand-transcribed or hand-formatted — this script owns exactly one thing, the
example pairs themselves, and never reimplements the examples-section format
the app builder owns.

Emits two committed artifacts, read by `lirevo-eval run`:

  crates/lirevo-eval/data/profiles/style-spike-v5.toml
  crates/lirevo-eval/data/corpus/style-spike-v5.jsonl

Each source case is emitted twice — once per arm — keeping `transcript` and
`expected` byte-identical across arms so the only variable is the system
prompt the profile carries. The fewshot arm is mapped to the examples matching
the source's OWN style: handing casual examples to a formal case would score
a casual output against a formal reference and make a working mechanism look
broken. Run from the repo root:

    python3 scripts/derive-style-spike-v5.py
"""

import json
import pathlib
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SEED = REPO / "crates/lirevo-eval/data/corpus/v1-seed.jsonl"
OUT_PROFILES = REPO / "crates/lirevo-eval/data/profiles/style-spike-v5.toml"
OUT = REPO / "crates/lirevo-eval/data/corpus/style-spike-v5.jsonl"

SOURCE_LANGS = {"it", "en"}
LANGS = ("it", "en")

HEADER = """\
# GENERATED by scripts/derive-style-spike-v5.py — DO NOT HAND-EDIT.
# Two-arm few-shot experiment, v5 (Gate 1 of the style-bootstrapping spike,
# the last mechanism after v1-v4 killed the style card).
#
# baseline        = lirevo_prompts::build_clean_system_prompt(lang), verbatim
# fewshot_casual  = lirevo_prompts::build_clean_system_prompt_with_examples(
#                     lang, EXAMPLES["casual"][lang])
# fewshot_formal  = lirevo_prompts::build_clean_system_prompt_with_examples(
#                     lang, EXAMPLES["formal"][lang])
#
# All three obtained via `lirevo-eval print-shipped-prompt`, never hand-
# transcribed — this file cannot silently diverge from what the app sends.
#
# post_assertions are IDENTICAL across all three on purpose: the only variable
# is the system prompt. They feed assertions_passed/total, never chrf or
# judge_style, so they cannot affect the verdict — but letting them vary would
# break the control for no benefit.
"""

# The only prompt content this script owns: three raw->final pairs per
# (style, language), shown to the model as-is by the shipped builder. Must be
# plausible dictations in the target style, and must not reuse any seed-corpus
# transcript or expected (the test asserts non-overlap).
EXAMPLES = {
    "casual": {
        "it": [
            ("scusa il ritardo sto arrivando tra dieci minuti", "scusa il ritardo, arrivo tra 10 min"),
            ("ok perfetto allora ci sentiamo domani mattina", "ok perfetto, ci sentiamo domani mattina"),
            ("no guarda oggi non ce la faccio proprio mi dispiace", "no guarda oggi non ce la faccio, mi dispiace"),
        ],
        "en": [
            ("sorry i'm late i'll be there in ten minutes", "sorry i'm late, be there in 10"),
            ("ok great so we'll talk tomorrow morning then", "ok great, talk tomorrow morning"),
            ("no honestly i can't make it today i'm sorry", "no honestly i can't make it today, sorry"),
        ],
    },
    "formal": {
        "it": [
            ("volevo chiedere se è possibile spostare la riunione a giovedì",
             "Buongiorno,\n\nLe scrivo per chiedere se sia possibile spostare la riunione a giovedì.\n\nCordiali saluti"),
            ("le mando in allegato il documento che mi aveva chiesto",
             "Buongiorno,\n\nLe invio in allegato il documento richiesto.\n\nCordiali saluti"),
            ("la ringrazio per la disponibilità di ieri è stato molto utile",
             "Buongiorno,\n\nLa ringrazio per la disponibilità di ieri: l'incontro è stato molto utile.\n\nCordiali saluti"),
        ],
        "en": [
            ("i wanted to ask whether we could move the meeting to thursday",
             "Dear all,\n\nI am writing to ask whether we could move the meeting to Thursday.\n\nBest regards"),
            ("i'm attaching the document you asked me for",
             "Dear all,\n\nPlease find attached the document you requested.\n\nBest regards"),
            ("thank you for your time yesterday it was really useful",
             "Dear all,\n\nThank you for your time yesterday — the discussion was very useful.\n\nBest regards"),
        ],
    },
}


def toml_multiline(s: str) -> str:
    # TOML """...""" tolerates a lone " but not """, and cannot end with ".
    # Assert rather than escape: a silent corruption here would produce a
    # subtly wrong prompt and a meaningless experiment.
    assert '"""' not in s, "prompt contains a TOML multi-line terminator"
    assert not s.endswith('"'), "prompt ends with a quote; TOML would mis-parse"
    return f'"""{s}"""'


def shipped_prompt(lang: str, examples: list[tuple[str, str]] | None = None) -> str:
    cmd = [
        "cargo",
        "run",
        "-q",
        "-p",
        "lirevo-eval",
        "--",
        "print-shipped-prompt",
        "--language",
        lang,
    ]
    if examples is not None:
        cmd += ["--examples-json", json.dumps(examples, ensure_ascii=False)]
    proc = subprocess.run(cmd, cwd=REPO, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        print(
            f"print-shipped-prompt --language {lang} exited {proc.returncode}:\n{proc.stderr}",
            file=sys.stderr,
        )
        raise SystemExit(1)
    if not proc.stdout:
        print(
            f"print-shipped-prompt --language {lang} produced an empty prompt; "
            "refusing to build a meaningless experiment on it",
            file=sys.stderr,
        )
        raise SystemExit(1)
    return proc.stdout


def emit_profiles(baseline: dict, fewshot: dict) -> str:
    arms = {
        "baseline": {lang: baseline[lang] for lang in LANGS},
        "fewshot_casual": {lang: fewshot["casual"][lang] for lang in LANGS},
        "fewshot_formal": {lang: fewshot["formal"][lang] for lang in LANGS},
    }
    out = [HEADER]
    for name, prompts in arms.items():
        out.append(f"\n[profile.{name}]")
        out.append("post_assertions = [")
        out.append('  { kind = "max_length_chars", value = 4000 },')
        out.append("]")
        out.append(f"\n[profile.{name}.system_prompts]")
        for lang in LANGS:
            out.append(f"{lang} = {toml_multiline(prompts[lang])}")
        out.append("")
    return "\n".join(out) + "\n"


# source profile -> {arm role: profile name in style-spike-v5.toml}
ARMS_BY_SOURCE = {
    "chat_casual": {
        "baseline": "baseline",
        "fewshot": "fewshot_casual",
    },
    "mail_formal": {
        "baseline": "baseline",
        "fewshot": "fewshot_formal",
    },
}


def main() -> int:
    if not SEED.exists():
        print(f"input not found: {SEED}", file=sys.stderr)
        return 1

    baseline = {lang: shipped_prompt(lang) for lang in LANGS}
    fewshot = {
        style: {lang: shipped_prompt(lang, EXAMPLES[style][lang]) for lang in LANGS}
        for style in ("casual", "formal")
    }
    OUT_PROFILES.write_text(emit_profiles(baseline, fewshot), encoding="utf-8")
    print(f"wrote 3 profiles → {OUT_PROFILES}")

    rows = []
    sources = 0
    for line in SEED.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        case = json.loads(line)
        arms = ARMS_BY_SOURCE.get(case["profile"])
        if arms is None or case["language"] not in SOURCE_LANGS:
            continue
        sources += 1
        for arm, profile in arms.items():
            out = dict(case)
            out["id"] = f"{case['id']}-{arm}"
            out["profile"] = profile
            out["tags"] = sorted(set(case.get("tags", [])) | {"style-spike-v5", f"arm:{arm}"})
            out["notes"] = (
                f"style-spike-v5 arm={arm} (profile {profile}); derived from "
                f"{case['id']} (source profile {case['profile']}). Generated by "
                f"scripts/derive-style-spike-v5.py — do not hand-edit."
            )
            rows.append(out)

    if not rows:
        print("no source cases matched; refusing to write an empty corpus", file=sys.stderr)
        return 1

    OUT.write_text(
        "".join(json.dumps(r, ensure_ascii=False) + "\n" for r in rows),
        encoding="utf-8",
    )
    print(f"wrote {len(rows)} cases ({sources} source cases × 2 arms) → {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
